### ISSUE TITLE
Need an example of using kube fixture

### ISSUE THREAD

**Issue by htambekar** [vapor-ware/kubetest#104]
Hi I am very new to python,

Tried to use kube and kubtest as fixture by referencing how to define a fixture as mentioned here.
https://docs.pytest.org/en/latest/index.html

Can you give a concrete example of defining fixture and using it to list all the pods?

**Comment by edaniszewski** [comment]
Sure thing -- I added a bunch of example tests showing different ways that kubetest can be used to get pods: https://github.com/vapor-ware/kubetest/tree/master/examples/get-all-pods-via-fixture

Let me know if those examples are helpful and if you have any questions about them.

**Comment by edaniszewski** [comment]
examples have been added to the repo. can reopen the issue if they are not sufficient or if you have more questions surrounding them
