### ISSUE TITLE
temporary namespace is not being deleted at the end of the test

### ISSUE THREAD

**Issue by eranreshef** [vapor-ware/kubetest#110]
I'm using kubetest to apply a deployment in a new temporary namespace and at the end of the test the deployment is being deleted but the namespace isn't.

**Comment by edaniszewski** [comment]
thanks for the report! could you provide some additional details, such as what version of kubetest you are using, version of kubernetes, and test/error output if there is any? I can look into this, but its difficult knowing where to look without some additional context.

**Comment by eranreshef** [comment]
python packages:
kubetest==0.1.0
kubernetes==9.0.0

kubernetes 1.12.9

pytest output:
```Testing started at 14:57 ...
/Users/erares01/.virtualenvs/sp0192/bin/python3.6 /Applications/PyCharm.app/Contents/helpers/pycharm/_jb_pytest_runner.py --target /Users/erares01/git/paas/splatt/tests/test_cli/test_poke.py::test_poke_deployment -- --kube-config kubeconfig --kube-disable
Launching pytest with arguments --kube-config kubeconfig --kube-disable /Users/erares01/git/paas/splatt/tests/test_cli/test_poke.py::test_poke_deployment in /Users/erares01/git/paas-labs/core-eran
============================= test session starts ==============================
platform darwin -- Python 3.6.5, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
rootdir: /Users/erares01/git
plugins: xdist-1.29.0, forked-1.0.2, datadir-1.3.0, kubetest-0.1.0, f5-sdk-3.0.20collected 1 item

../../paas/splatt/tests/test_cli/test_poke.py                           [100%]

========================== 1 passed in 11.48 seconds ===========================

Process finished with exit code 0
.

**Comment by edaniszewski** [comment]
I think I see what the issue may be here. From the test output, I see that the `--kube-disable` flag is being used. That *should* disable kubetest from doing much of anything, but it appears that a check for this is missing where it previously used to be, so now parts of the kubetest setup/teardown are disabled (including ns cleanup), but the actual test will run and create the namespace.

I'll put together a patch shortly which should fix this. I think the semantics/usage around `--kube-disable` should also be revisited, so I'll spend some time looking in to how that can be tightened up afterwards.

**Comment by eranreshef** [comment]
thanks!

On a different matter, I want to add support to more k8s objects such as statefulsets and daemonsets.

I'm already working on a PR, is that ok?

**Comment by edaniszewski** [comment]
yeah! that would be great -- a preemptive thanks for your contributions! (:

**Comment by eranreshef** [comment]
tested and verified 👍 
Thanks!
