### ISSUE TITLE
kube fixture to contain some info about the cluster

### ISSUE THREAD

**Issue by eranreshef** [vapor-ware/kubetest#118]
Hi,

How about having the kube fixture object to contain some info about the cluster?
I am talking about info that can be extracted from the kubeconfig file which is the cluster name and api-server address.

**Comment by edaniszewski** [comment]
+1 to this, I think it would be great

I do recall trying to access the loaded kubeconfig directly previously for some other task and having some difficulty, but I can take another look into it
