### ISSUE TITLE
Getting type errors in the Response Object

### ISSUE THREAD

**Issue by plyte** [vapor-ware/kubetest#128]
I'm getting a type error in the kubetest.response.Response object after switching from 0.3.2 to 0.3.3. Using the http_proxy_get method from the Pod object I get the following error after sending any request on an endpoint (that works in 0.3.2). 

```
data = resp.json()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <kubetest.response.Response object at 0x000002E181349780>

    def json(self):
        """Convert the response data to JSON.
    
        If the response data is not valid JSON, an error will be raised.
    
        Returns:
            dict: The JSON data.
        """
        # This should generally be the case, since the primary source of Response
        # instances are the HTTP methods on Pods (e.g. http_proxy_get), where
        # `_preload_content=False`. Should that be set to True, it will not return
        # the HTTPResponse but will instead return the response data formatted as
        # the type specified in the `response_type` param.
        #
        # Note that I have found setting _preload_content to True (the default value
        # for the Kubernetes client) to be difficult to deal with from a generic interface
        # because it requires you to know the expected output ("str", "dict", ...)
        # and pass that in as a param, where that could really be abstracted away from
        # the user. For that reason, it is currently set to False -- this may change
        # in the future if desired.
        if isinstance(self.data, urllib3.HTTPResponse):
            return json.loads(self.data.data)
    
        # the response data comes back as a string formatted as a python
        # dictionary might be, where the inner quotes are single quotes
        # (') instead of the double quotes (") expected by JSON standard.
        # to remedy this, we just replace single quotes with double quotes.
>       data = self.data.replace("'", '"')
E       TypeError: a bytes-like object is required, not 'str'

..\kubetest\response.py:59: TypeError
```

**Comment by plyte** [comment]
I figured out the issue, the recent switch from True to False on the _preload_content field on lines 227 and 296 of pod.py causes issues when the connection isn't accepted by the pod (i.e. incorrect endpoint or the pod not having ports exposed). Once this happens the errors are sent via the exception handle and output as:

When the endpoint is incorrect
```
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>\n'
``` 
which causes a json.decoder.JSONDecodeError
or when the pod doesn't have the port exposed which is then output as a byte string when the resulting data isn't of type urllib3 output below:
```
b"Error: 'dial tcp 172.17.0.4:80: connect: connection refused'\nTrying to reach: 'http://172.17.0.4/?abc=123'"
```
Should this be handled in another manner or at least shown to the user?

If this is intended behavior then I'll go ahead and close the issue.

The yaml file used is as shown below:

```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: flask
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: plyteuth/flask-example
        ports:
        - name: http
          containerPort: 8000
```

Take out the port shown in the yaml file to recreate the second output shown above and change the endpoint to something other than / to show the first output.

**Comment by edaniszewski** [comment]
@plyte -- sorry for the long delay in response, I was out on vacation and am just getting caught up. thanks for digging into this and providing details on how to reproduce. I was able to reproduce on my end and came up with a solution that I think handles these cases better (see #129)

With the linked PR, errors like the connection error or invalid endpoint will fail the ast load, will fallback to `json.loads`, and from there should fail with the familiar JSON decode error, and I believe pytest will output the offending string so it gets displayed to the user.

Sorry again for the quick 0.3.3 patch which didn't end up working well and for the delay in getting this patch up!
