### ISSUE TITLE
change loading order of Objects via the ApiObject

### ISSUE THREAD

**Issue by plyte** [vapor-ware/kubetest#134]
Could we change the loading order to include Statefulsets before Deployments? If I have a postgres database as a stateful set its likely my deployment that relies on it will not receive it at run time in time.

**Comment by edaniszewski** [comment]
@plyte  good catch -- that definitely makes sense. I opened up #134 which should resolve this, let me know if it looks good to you.

**Comment by plyte** [comment]
@edaniszewski Looks perfect! Thanks!
