### ISSUE TITLE
Parametrized Tests Fail to Create Namespace

### ISSUE THREAD

**Issue by bjohnson121** [vapor-ware/kubetest#146]
Details:
- Working in EKS 113
- Pytest Version 5.2.1
- Kubetest version 0.4.3
- Python Version 3.7.4

If you have a test that is marked parametrized for each test iteration, kubetest will create a temporary namespace that is something like `test-name[data#]-id` where data is the name of the dataset passed in and the # represents the the index of the data for the given test.

Square brackets are not allowed in the namespace name and the test setup fails.

A use case for parametrized tests would be to pass a list of pod names upon which you want to perform the same actions.

**Comment by edaniszewski** [comment]
Good catch - thanks for opening up this issue!

I'm a bit bogged down with other things ATM, so I won't be able to get to this immediately, but possibly by the end of this week/beginning of next week I can take a stab at fixing this and cutting a new release.
