### ISSUE TITLE
When using kubeconfig fixture, test namespaces are not cleaned up.

### ISSUE THREAD

**Issue by lfn3** [vapor-ware/kubetest#154]
We generate our k8s yaml files from a template, and feed these directly into the kube client using similar mechanisms to what is currently in the codebase for the load manifest. Because of this we don't use the markers, but do use the `kube` fixture.
We also provide the `kubeconfig` using a fixture to point to a config file in our repo.

We aren't seeing the namespaces being cleaned up at end of the test run.

I think this is because of [this line](https://github.com/vapor-ware/kubetest/blob/075ea9f98826ffee2dca1a49a8af080d10591857/kubetest/plugin.py#L265) of code which doesn't seem to align with the `pytest_runtest_setup` hook above.

**Comment by edaniszewski** [comment]
Thanks for opening this issue! I was able to reproduce locally, and I believe you are right. It appears that the test namespace cleanup is not happening when the kubeconfig is not provided via command line.

I'll work on a fix for this shortly
