### ISSUE TITLE
Can this be used to run on class based scope instead of function?

### ISSUE THREAD

**Issue by AndersonReyes** [vapor-ware/kubetest#171]
Creating resources every function for us is too slow. Using it at the class scope is more efficient.

**Comment by edaniszewski** [comment]
Good question! I haven't looked into what it would take to support this from the pytest side of things, but I imagine that it would be possible. I can spend some time over the next few days looking into what it would take to make this happen.

**Comment by AndersonReyes** [comment]
@edaniszewski dope we'll look through code base too @danieldiamond we can give it a shot on your fork, I just wanted to make sure if the functionality already existed before trying to do double the work

**Comment by AndersonReyes** [comment]
To tricky part is right now the test registration 
 resource creation happens at https://github.com/vapor-ware/kubetest/blob/master/kubetest/plugin.py#L238 which runs for each test item I believe. Pytest not supporting multi scoped fixtures means duplicate code too which is annoying. Hmmm
