### ISSUE TITLE
support for replicaset

### ISSUE THREAD

**Issue by acidnag** [vapor-ware/kubetest#177]
I did not find support for replicasets in kubetest (apologies in advance if I overlooked, please point me to its usage).
As a user, I would like to be able to test replicasets in a namespace.

**Comment by edaniszewski** [comment]
Hi -- thanks for the feature request! You are right in that there are currently no object mappings for replica sets, but it should be pretty straightforward to add.

I'm a bit busy today, but if you give me a couple of days, I should be able to throw together support for replicasets and cut a new release which includes it.

**Comment by edaniszewski** [comment]
released in `0.7.0`

**Comment by acidnag** [comment]
thank you
